### ISSUE TITLE
Rename schema to plugin

### ISSUE THREAD

**Issue by Zethson** [laminlabs/lamindb#1437]
We agreed to do so on Slack. Renaming this is sadly a mess.

- [ ] Consider renaming the `lnschema-X` to `X-plugin`
- [ ]  Rename the `--schema` parameter in `lamindb`
- [ ]  Update all docs everywhere

**Comment by falexwolf** [comment]
I wouldn't do this in particular because it's pretty clear that there will be apps that consitute plain schema modules vs. much richer plugins.

What the SQL database cares about is only the schema component, and `schema` is the name for it. Plug-in is in fact degrading the clarity. Hence, I'd keep this as is.
