### ISSUE TITLE
System error on re-running CellMarker.add_synonym

### ISSUE THREAD

**Issue by insavchuk** [laminlabs/lamindb#1759]
<img width="1424" alt="Screenshot 2024-07-27 at 17 46 02" src="https://github.com/user-attachments/assets/6a961838-907b-4793-b479-cd7c59c892f3">

**Comment by insavchuk** [comment]
Full traceback:

**Comment by insavchuk** [comment]
error occurs once in ~10 re-runs of the same cell.

**Comment by Zethson** [comment]
Dear @insavchuk,

thank you for the report! I have a kind request: Could you please always try to copy and paste code and error messages instead of posting screenshots? This makes it much easier for us to debug.

In a fresh instance,
```
import bionty as bt
bt.settings.organism = "human"

bt.CellMarker(name="TBX21").save()
bt.CellMarker.search("TBX21").first().add_synonyms("T-bet")
```

works for me.

Now the issue that you're running into is that you're trying to add a synonym to a record which already is a synonym of a record.

In other words,

```
bt.CellMarker.search(uid="ppzJGtvJuKYK).one()
```

already has the synonym `T-bet` as you can see in your screenshot. I have the impression that your search returns a different record than the one that already has the synonym. Then you are trying to add the synonym to a different record but it's already associated with one.

Could you please ensure that:

```
bt.CellMarker.search("TBX21", field="name").df()
```

only has a single hit?

**Comment by insavchuk** [comment]
Hi Lukas, you had the right suspicion here - I realized that prior to synonym lookup, I had created a new entry for TBX21, and then added a synonym "T-bet" to that. Thanks!
```
bt.CellMarker.search("T-bet").df()
```
<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>uid</th>
      <th>name</th>
      <th>synonyms</th>
      <th>gene_symbol</th>
      <th>ncbi_gene_id</th>
      <th>uniprotkb_id</th>
      <th>organism_id</th>
      <th>public_source_id</th>
      <th>run_id</th>
      <th>created_by_id</th>
      <th>updated_at</th>
    </tr>
    <tr>
      <th>id</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>563</th>
      <td>7ZzRYAfMHu72</td>
      <td>TBET</td>
      <td>T bet|T-BET</td>
      <td>TBX21</td>
      <td>30009</td>
      <td>Q9UL17</td>
      <td>1</td>
      <td>18.0</td>
      <td>None</td>
      <td>6</td>
      <td>2024-07-27 15:40:31.659374+00:00</td>
    </tr>
    <tr>
      <th>555</th>
      <td>ppzJGtvJuKYK</td>
      <td>TBX21</td>
      <td>T-bet</td>
      <td>None</td>
      <td>None</td>
      <td>None</td>
      <td>1</td>
      <td>NaN</td>
      <td>None</td>
      <td>6</td>
      <td>2024-07-27 15:52:22.129516+00:00</td>
    </tr>
  </tbody>
</table>
</div>

**Comment by Zethson** [comment]
Great! I'll improve the error message to give clearer guidance for the future.
