### ISSUE TITLE
🚸 ln.track should prompt to enter any key instead of y or n with an error

### ISSUE THREAD

**Issue by Koncopd** [laminlabs/lamindb#2265]
### Add a description

subj

**Comment by falexwolf** [comment]
Can then also make this message analogous so that it no longer raises an error but the same analogous dialogue in a notebook.

<img width="671" alt="image" src="https://github.com/user-attachments/assets/b5ec29ed-7f64-49b2-b9a7-769b490e4b74" />

**Comment by ap--** [comment]
Just fyi, because a user ran into this:

There can be a deadlock in older jupyterlab versions where when the input is displayed and a user manually reruns the cell, the kernel deadlocks. Might be worth not showing the input when running in older jupyter lab versions

https://github.com/jupyterlab/jupyterlab/pull/8713
https://github.com/jupyterlab/jupyterlab/pull/16032

Seems to be fixed in:
- **3.x branch:** 3.1.0+
- **4.x branch:** 4.2.0+

**Comment by falexwolf** [comment]
Thanks for sharing! We'll account for this in one way or the other. 👌

**Comment by falexwolf** [comment]
This is comprehensively addressed here:

- https://github.com/laminlabs/lamindb/pull/2308
