### ISSUE TITLE
Shorten lamindb import time

### ISSUE THREAD

**Issue by sunnyosun** [laminlabs/lamindb#401]
Currently takes ~11s

**Comment by Zethson** [comment]
I created an import log which can be viewed with https://github.com/nschloe/tuna

```
python -X importtime -c "import lamindb as ln" 2> lamindb_import.log
tuna lamindb_import.log
```
[lamindb_import.log](https://github.com/laminlabs/lamindb/files/10530044/lamindb_import.log)

This then looks something like 

![image](https://user-images.githubusercontent.com/21954664/215335782-a1d7602a-dcee-4d2e-911d-232372b5be2e.png)

So the biggest offenders are `lndb_setup` and `lamindb_check_versions`

**Comment by Zethson** [comment]
As far as I know there's a couple of ways to speed up application startup and the whole performance of a package:

1. **Lazily import packages.** We should only do this when we can ensure that the function importing the module is not called repeatedly. Else wise, we'll keep scanning the environment to find the package to import which can get expensive over time.
2. **Lazily run startup functions.** This is a tradeoff between startup time and application performance. We're basically moving some expensive startup imports to functions that users have to call anyways.
3. **from imports**
Instead of

```
import math
value = math.sqrt(50)
```

we do

```
from math import sqrt
value = sqrt(50)
```

5. **remove unused imports & reduce dependency sets in general**. Generally flake8 should annoy us about the former and we hopefully figure out the latter.

**Comment by Zethson** [comment]
I can't look into `lndb_setup` yet because I don't have access so I looked into `_check_versions` instead.

```
from bionty import __version__ as bionty_v
from lndb_setup import __version__ as lndb_setup_v
from lnschema_core import __version__ as lnschema_core_v
from nbproject import __version__ as nbproject_v
from packaging import version

if version.parse(lndb_setup_v) != version.parse("0.30.10"):
    raise RuntimeError("Upgrade lndb_setup! pip install lndb_setup==0.30.10")

if version.parse(lnschema_core_v) != version.parse("0.25.3"):
    raise RuntimeError("lamindb needs lnschema_core==0.25.3")

if version.parse(bionty_v) != version.parse("0.6.4"):
    raise RuntimeError("lamindb needs bionty==0.6.4")

if version.parse(nbproject_v) < version.parse("0.8.0"):
    raise RuntimeError("lamindb needs nbproject>=0.8.0")
```

All of these required versions are pinned in the `pyproject.toml`

```
dependencies = [
    # Lamin pinned packages
    "lndb_setup==0.30.10",
    "lnschema_core==0.25.3",
    "bionty==0.6.4",
    "nbproject>=0.8.0",
]
```

Hence, the installation would already raise errors if for some reason this specific version of lamindb were installed in an environment with the wrong set of dependencies.

In any case, I noticed that the `__version__` imports import all of the respective packages.

![image](https://user-images.githubusercontent.com/21954664/215338356-fc1b3c6e-3aa5-43e4-81e8-5eafe2b16886.png)

My guess is when importing `__version__` all other statements and imports of the packages are also executed.

Hence,
```
>>> from importlib.metadata import version
>>> version('bionty')
'0.6.4'
```

etc might be faster. I'll try this later.

**Comment by falexwolf** [comment]
Thanks for benchmarking this in-depth, Lukas!

We haven't gotten around to optimizing anything for LaminDB yet, but I did similar benchmarks for other packages in the past. :sweat_smile: 

Let's keep this open and decide whether to act on anything - I think the current situation is a lot better than what we had in early December already, but @sunnyosun will speak more to this.

To this note:

> Hence, the installation would already raise errors if for some reason this specific version of lamindb were installed in an environment with the wrong set of dependencies.

You're right (edit: I think, pip raises red-colored "errors" but will still successfully install say lamindb; some users might ignore these "errors" as they behave more like warnings)! The `._check_versions.py` piece is mostly meant for devs who `pip install -e .` and update via `git pull --rebase`. This is currently the common workflow for us, and within it, `.check_versions` is pivotal for raising early errors related to inconsistent local environments. We had added similar functionality to Scanpy back in the days.

**Comment by sunnyosun** [comment]
Thank you for such deep analysis @Zethson! Yes, we improved from 11s → 5s in the past month.

I think 5s is acceptable for now, if importing the version as you suggested can give immediate improvement, that would be great! Otherwise maybe we could look into this a bit more in the future when needed. 😄
