### ISSUE TITLE
Improve CI run time

### ISSUE THREAD

**Issue by sunnyosun** [laminlabs/lamindb#482]
- The notebooks take too long to run and slow down the dev speed. Especially the notebooks that use cloud storage.
- Both installing dependencies and linting take 1-2min each.

I've tried to shorten it to ~6-8min a few times in the past months, and now it's ~12min again.

The notebooks in `guide/` need to run sequentially, but the ones in `faq/` can probably be in parallel.

- @falexwolf Is this notebook needed in CI, can we move it to lndb-setup? https://lamin.ai/docs/db/faq/storage

- Can this notebook be combined into an existing one? https://lamin.ai/docs/db/faq/settings, for instance, this? https://lamin.ai/docs/db/faq/ingest-same-file-twice

- Similarly, does this notebook needs to be run in CI? Can it just be a note? https://lamin.ai/docs/db/faq/lazy-loading

**Comment by Zethson** [comment]
Collecting a bunch of random thoughts that might help. Don't read them all as "MUST DOS", but starting points for further discussion, please.

1. Something that I wanted to suggest anyways -> I'd separate the different testing/building steps into their own workflows. We could have build/lint/publish/docs etc workflows separately. Depending on resource availability these can then already start in parallel.
2. Testing should be done with pytest and not expensive notebooks (aka integration tests). Using notebooks that run whole functions as "tests" is also a cheap and misleading way to increase codecoverage. Think that bionty is a clear "abuser" of this.
3. I'd also encourage you to run the notebooks that can be run in parallel with a CI matrix. Either via pytest (through a nox configuration) or with a workflow that just executes them until failure (raw example -> https://github.com/theislab/ehrapy/blob/development/.github/workflows/run_notebooks.yml)
4. Random idea? Is it useful/possible to cache some jupyter notebook output?

**Comment by falexwolf** [comment]
Thanks for all the great suggestions!

Here comes [a page for a review meeting](https://www.notion.so/laminlabs/draft-CI-review-2023-02-08-f4790c56e86840da917cc3a5d58e6149) in which we can discuss all of them in-depth and follow up with what we want to implement to solve these performance issues, and also make progress on quality.

Some quick high-level responses to Lukas’s point here to give a gist for why they haven't (yet) been implemented
1. Except for linting, all other steps require each other (running integration tests produces the notebook output for building the docs etc.) - linting used to take negligible time
2. Fully agreed that just running a function isn't a proper test; I think it's a different story when outputs are checked with asserts (is the case in many notebooks); depending on where packages are in their life cycle they'll have more or less unit tests both across `tests` and `faq` (as opposed to integration tests); all production grade packages will have fine-grained unit tests over time
3. Most integration tests are in fact a notebook pipeline and cannot be parallelized; we'll need to figure out a strategy that's aware of notebook pipelines, parallelized notebooks, and all ways unit tests can be scaled
4. We're already caching it across build & docs steps, build time would be twice as long otherwise; not sure about within-package-across-ci-run caching; across-package caching is in place using inter-sphinx but the current docs roadmap will require storing artifacts (other solutions welcome!) to assemble more comprehensive docs sites across packages
5. Agreed! We're only testing 3.8., 3.9, 3.10 on a case-by-case basis; most packages typically only run on 3.9; 3.7 was sometimes there as GCP Vertex still had it running as a default a few months ago and we're told many enterprises work on old versions

**Comment by sunnyosun** [comment]
Consider turning the following FAQ notebooks into markdowns and test scripts:

- https://lamin.ai/docs/db/faq/storage
- https://lamin.ai/docs/db/faq/select
- https://lamin.ai/docs/db/faq/lazy-loading
